<?if(Mage::getStoreConfig('blog/blog/userte')):?>
<script src="<?php echo $this->getSkinUrl('') ?>Blog/js/tiny_mce/tiny_mce.js"></script>
<script src="<?php echo $this->getSkinUrl('') ?>Blog/js/init_rte.js"></script>

<script>
	// Init rte
	BlogIntId = setInterval(
		function(){
			if(typeof tinyMCE != 'undefined' && $('anchor-content')){
				initRTE();
				clearInterval(BlogIntId);
			}
		}
	,500)
</script>
<?endif;?>
